services:

  bot:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    restart: unless-stopped


  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data: {}
