services:

  bot:
    build: .
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    command: npm start

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: {}