---
- name: Setup AWS Amazon Linux Instance
  hosts: all
  become: no
  vars:
    the_user: "{{ ansible_user_id }}"
    node_version: 20.15.1
  tasks:
    - name: Clone bot repo
      become: no
      git:
        repo: "{{ bot_repo }}"
        dest: "{{ ansible_env.HOME }}/{{ bot_name }}"
      tags:
        - project

    - name: Copy env file
      become: no
      copy:
        src: ../.env
        dest: "{{ ansible_env.HOME }}/{{ bot_name }}/.env"
      tags:
        - project
        - env

    - name: Install bot dependencies with Yarn
      become: no
      shell: >
        . {{ ansible_env.HOME }}/.nvm/nvm.sh && cd {{ ansible_env.HOME }}/{{ bot_name }} && yarn install
      tags:
        - project

    - name: Build bot
      become: no
      shell: >
        . {{ ansible_env.HOME }}/.nvm/nvm.sh && cd {{ ansible_env.HOME }}/{{ bot_name }} && yarn build
      tags:
        - project

    - name: Create systemd service
      become: yes
      ansible.builtin.template:
        src: ../systemd.service.j2
        dest: /etc/systemd/system/{{ bot_name }}.service
      tags:
        - project

    - name: Start systemd service on boot
      become: yes
      shell: >
        systemctl enable {{ bot_name }}
      tags:
        - project

    - name: Start systemd service now
      become: yes
      shell: >
        systemctl start {{ bot_name }}
      tags:
        - project
        - start
